### ISSUE TITLE
[Docs] Some Rendez-Vous Protocols

### ISSUE THREAD

**Issue by DaniElectra** [kinnay/NintendoClients#108]
These protocols appear on Rayman Legends Challenges App. We now have documentation of the Title Storage protocol (for which you had the protocol ID, but no docs) and two other protocols, one being the admin version of title storage.

The OLS storage seems to be a custom protocol for Rayman Legends, by looking at the structure contents.

[OLSStorageProtocol.md](https://github.com/kinnay/NintendoClients/files/11587033/OLSStorageProtocol.md)
[TitleStorageAdminProtocol.md](https://github.com/kinnay/NintendoClients/files/11587034/TitleStorageAdminProtocol.md)
[TitleStorageProtocol.md](https://github.com/kinnay/NintendoClients/files/11587035/TitleStorageProtocol.md)

**Comment by kinnay** [comment]
I updated the wiki :+1:
