### ISSUE TITLE
[Wiki] DDL tree paramater type 3

### ISSUE THREAD

**Issue by DaniElectra** [kinnay/NintendoClients#118]
On Ubisoft games, some protocols like `Tracking 3` include parameters with parameter type 3. After further investigation, it looks like paramater type 3 means that the `Parameter` is present both in the *request* and the *response* of a method.

This behavior has been verified on the PC version of Rayman Legends, where the `userInfo` parameter on the `Tracking3::SendUserInfo` method is present in both the request and response.

**Comment by kinnay** [comment]
Interesting, I updated the wiki page 👍
