### ISSUE TITLE
Support Request for Nintendo Switch Firmware 18.1.0 Update

### ISSUE THREAD

**Issue by pccavar** [kinnay/NintendoClients#132]
The Nintendo Switch firmware version 18.1.0 has been released, and certain games now frequently prompt for updates. While you may already be working on this, we would greatly appreciate it if this issue could be addressed.

**Comment by kinnay** [comment]
Thanks to @TheGreatRambler for implementing this (#133).

**Comment by pccavar** [comment]
Thank you so much, @TheGreatRambler, for your prompt implementation for the Nintendo Switch firmware 18.1.0 update.

Also, thank you, @kinnay, for coordinating and merging the pull request. It’s wonderful to see such a collaborative effort. Keep up the great work, everyone!

**Comment by TheGreatRambler** [comment]
> The Nintendo Switch firmware version 18.1.0 has been released, and certain games now frequently prompt for updates. While you may already be working on this, we would greatly appreciate it if this issue could be addressed.

I was wondering about this. I'll have to pay closer attention to updates now.
