### ISSUE TITLE
`User-Agent` header is removed for some requests since 18.0

### ISSUE THREAD

**Issue by Coxxs** [kinnay/NintendoClients#134]
Example:
17.x:
```
POST /v7/challenge HTTP/1.1
Host: dauth-lp1.ndas.srv.nintendo.net
User-Agent: libcurl (nnDauth; 16f4553f-9eee-4e39-9b61-59bc7c99b7c8; SDK 17.5.0.0)
Accept: */*
X-Nintendo-PowerState: FA
Content-Length: 17
Content-Type: application/x-www-form-urlencoded
```

18.0.0 / 18.1.0:
```
POST /v7/challenge HTTP/1.1
Host: dauth-lp1.ndas.srv.nintendo.net
Accept: */*
Content-Type: application/x-www-form-urlencoded
X-Nintendo-PowerState: FA
Content-Length: 17
```
The position for `Content-Type` has also changed.

May need to update NintendoClients to remove the `User-Agent` for these requests.

**Comment by kinnay** [comment]
Good catch. I'll do some investigation. It looks like they have rewritten their HTTP client.

**Comment by kinnay** [comment]
It seems that only the dauth flow was affected. Other HTTP clients still have the same header order as before. I've pushed a fix. Thanks for notifying me.
