### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by kinnay** [kinnay/NintendoClients#136]
See title, apparently `pkg_resources` is deprecated. There are two alternatives:
* Replacing it with `importlib.resources`. This would require bumping the minimum Python version up to 3.11.
* Loading resources from a path relative to `__file__`. This would not work in some specific cases, such as when the package is imported from a zip file. I'm not sure if we need to support that situation though.

Any thoughts?

**Comment by TheGreatRambler** [comment]
I personally use NintendoClients (and most Python 3+ libraries) under version 3.11 so that version bump would not be a problem for me

**Comment by kinnay** [comment]
This is fixed in fdfc4c1548829fea29409ed46d24b812f56e6301.
