### ISSUE TITLE
When i open setup.py the cmd opens and close in 2 seconds

### ISSUE THREAD

**Issue by Nintendo-we** [kinnay/NintendoClients#137]
Please help i want to be online please
i have the latest python and i used the pip cmd to download the nintendo clients now what i do PLEASE HELP

**Comment by kinnay** [comment]
> I want to be online

What do you mean? What exactly is your goal?

The best way to get started is to check out one of the [example scripts](https://github.com/kinnay/NintendoClients/tree/master/examples), the [package docs](https://nintendoclients.readthedocs.io/en/latest/) or the [wiki](https://github.com/kinnay/NintendoClients/wiki), but I'm not sure if NintendoClients is the correct tool for what you are doing.
