### ISSUE TITLE
when i execute setup.py it says

### ISSUE THREAD

**Issue by Nintendo-we** [kinnay/NintendoClients#138]
Traceback (most recent call last):
  File "C:\Users\Infinite\Downloads\NintendoClients-2.2.1\NintendoClients-2.2.1\setup.py", line 2, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'

**Comment by kinnay** [comment]
I would recommend installing the package with pip, instead of running setup.py manually. Otherwise, find a way to install setuptools on your machine. I just discovered that there is a Python discord: https://discord.gg/python. People might be able to help you there.
