### ISSUE TITLE
Mario Kart 8 Deluxe example script not working

### ISSUE THREAD

**Issue by Simonx22** [Kinnay/NintendoClients#15]
Hi, I recently noticed that example_mariokartdeluxe.py doesn't seem to work anymore. Did they possibly disable the guest login? 
The error I get is ``nintendo.nex.common.RMCError: RendezVous::InvalidUsername (0x80030064)``

**Comment by Kinnay** [comment]
That's bad news, and there's nothing we can do about it: they deleted the guest account. Now the whole dauth/aauth/baas procedure is the only way to log in. A mitm is probably the easiest way to obtain a nex token (I think it's returned by /1.0.0/application/token).

**Comment by Simonx22** [comment]
I'll close this issue now that you've added a note in the RADME.md file.
