### ISSUE TITLE
Decrypting downloaded MM2 levels

### ISSUE THREAD

**Issue by TheGreatRambler** [Kinnay/NintendoClients#19]
I want to preface by saying, thank you! This project is absolutely fantastic! About the SMM2 example, you download the level into `level.bin`. Is this file equivilent to one that can be parsed by [simontime's decryptor](https://github.com/simontime/SMM2CourseDecryptor) or the [partrick level editor](https://github.com/RedDuckss/partrick)? That is, is the file in `bcd` format? Thank you!

**Comment by Kinnay** [comment]
Yes it is :wink:
