### ISSUE TITLE
Nintendo 3DS PRUDP V1

### ISSUE THREAD

**Issue by tastymeatball** [Kinnay/NintendoClients#2]
Hi
I tried to create "server" for Metroid Prime FF to look into the packets just for fun.
But I have a problem with the packet signature in PRUDP V1.
The connection with the 3DS seems a little bit simpler as opposed to the Wii U. It just connects to nasc.nintendowifi.net, sends a request and gets a response that inlucdes an IP (Key named locator in the response) that is base64 encoded and a token that I have no idea how it is encoded. After it closes the connection to nasc it directly sends a SYN PRUDP V1 packet to the Game Server. The game seems to just accept my SYN packet from my server without a signature but the CONNECT packet that follows it will not accept. My CONNECT response is the exactly the same as the one from the real server, except the packet signature and the session ID. But the session ID seems to be a random number anyway so it shouldn't cause the game to not accept my packet.

I guess the 3DS doesn't use a secure key to calculate the signature because there is no such thing as a secure server, except it is hidden in the token from the nasc.
So the real problem I'm facing is how can I get the access key of Metroid Prime FF. Do you have any idea?

**Comment by Kinnay** [comment]
Hello,

The 3DS connection is actually pretty similar to the Wii U. The only difference is that 3DS games retrieve the address of the authentication server from nasc.nintendowifi.net and Wii U games request it from account.nintendo.net.

The token in the nasc response probably contains secret data that can only be decrypted by Nintendo's servers. You shouldn't need to worry about it. Wii U games pass the token to the authentication server as parameter in the [LoginEx](https://github.com/Kinnay/NintendoClients/wiki/Authentication-Protocol#2-loginex) method. I guess 3DS games do the same. [LoginEx](https://github.com/Kinnay/NintendoClients/wiki/Authentication-Protocol#2-loginex) then returns the address of the secure server and some other information. This is how the 3DS knows where it can find the secure server.

You are right that the session id is just a random number and it shouldn't cause any issues, but keep in mind that the packet signature depends on the content of the packet. If you use a different session id than the real server, you can't blindly copy the packet signature from the real server.

The only way to find the access key is by looking at the executable of the game. I don't know how much experience you have with this kind of things, but a relatively easy way to find it is to load the executable into IDA and look for a string that consists of exactly 8 lowercase hex digits.

**Comment by Kinnay** [comment]
There must be an access key somewhere, and I'm pretty sure they only contain hex digits in 3DS games too. The access key is not the only thing of the friend server that's different from other 3DS/Wii U servers, and (for example) the access key of Mario Kart 7 is 6181dff1.

The access key of SSB4 does indeed seem to be 2869ba38, although I haven't tested it myself either. If you give me your code.bin I can see if I can find the access key myself. Or maybe you can try to brute force it if you have a packet capture with the real server, because there are only 2^32 possible access keys and the HMAC calculation can be done pretty fast.

**Comment by tastymeatball** [comment]
I guess I found the access key now. The game doesn't have the access key directly written into its code instead its saved in a plain text .ini file that is located in romfs/ini/skuinfo/.
This file also includes the CTR Game ServerID and a bunch of other stuff.
Here is the complete text of the file

CTR ProductCode = CTR-P-BCAP
CTR UniqueID = 0x01752
CTR OtherUniqueIDForDSDownload = 0x01753
CTR GameServerID = 0x0016CE00
CTR GameServerAccessKey = f79fb3c5
CTR AccessibleSaveDataId1 = 0x01753

Yes just 6 lines of plain text no more

**Comment by Kinnay** [comment]
Interesting. I'll add it to the [Game Server List](https://github.com/Kinnay/NintendoClients/wiki/Game-Server-List).

Feel free to reopen this issue if you have any further questions.

**Comment by Kinnay** [comment]
I don't see anything wrong with your python code, but I think you meant you stripped the first 4 bytes instead of the first 6 bytes. Could you send me your packet dump? Maybe I can find out why the packet signature is different.

**Comment by tastymeatball** [comment]
I've found it out myself. Don't know if this is just different for 3DS games or if this applies to Wii U games too but in the SYN packet when the consoles doesn't know the connection signature of the server it doesn't use it for calculation at all. In other words commenting the connection signature update line should fix the problem.

**Comment by Kinnay** [comment]
Nice finding! I checked my client code ([prudp.py](https://github.com/Kinnay/NintendoClients/blob/master/nintendo/nex/prudp.py)), and you're right: if it hasn't received the connection signature yet, it doesn't use it for the packet signature calculation at all. I don't know how this happened, but I must have made a mistake while writing that part of the wiki page. I'll fix it. Thanks!

I also see why you said that you removed the first -6- bytes from the packet now. I completely forgot about the magic number 😅.

**Comment by tastymeatball** [comment]
Now I have a problem with the Kerberos key.
Your wiki states you need a NEX password to generate a kerberos key but I don't get such a thing. The nasc just returns a locator, retry, returncd, token and datetime value. And if I read your code right you use the nintendo network account password to generate the key. But a 3DS doesn't have this because it doesn't use a nintendo network account. Giving the game nothing (buffer length 0) or just 00 bytes as kerberos data gives an error in game with states that it couldn't connect to the server.
And to just check if I understood the wiki page right
the whole kerberos Ticket (140 bytes length) consists of the secure key, server pid and ticket data, where the first 32 bytes are the secure key, the next 4 bytes the server pid and the rest the ticket info. The ticket info is practically not needed because the game can't read it anyway.

**Comment by Kinnay** [comment]
The key is not derived from the nintendo network account password but from the NEX password. NEX username/password are automatically generated by the server the first time you log in, and can not be changed manually. The Wii U account server returns your NEX username/password when you request a NEX token, but I have no idea how to obtain your NEX password from 3DS servers unfortunately.

The first 32 bytes of the kerberos ticket are indeed the secure key, the next 4 bytes the server pid, and the rest the ticket info. But the ticket is smaller than 140 bytes, normally, where did you get that number?

**Comment by tastymeatball** [comment]
That is the LoginEx Response from the MPFF auth server from nintendo (already decrypted)
400100000A01060000000280000001000100806BEC078C000000F682DBE86C306DC68F5DF461E21CA86841D4560B18F1BE5552B81841AADB5B5C310918A046F9E4B29C2949748F4B38396A008032A0FF27AA0E7C770B493B8A30AC85980250DE2BE36BC75ACBF02C0A76A769EA2AE998F6FD1637A0378B696B2E043FB473A2A5455C9FBA8C5365F39C240B11508814416C0F78075D2C8F222216FF7882874DC82E7791A796BD015E0000004D007072756470733A2F616464726573733D33342E3230382E3136362E3230323B706F72743D34303436313B4349443D313B5049443D323B7369643D313B73747265616D3D31303B747970653D320000000000010000B378A08A1F00000039006272616E63683A6F726967696E2F72656C656173652F6E67732F332E392E782E32303078206275696C643A335F395F31375F323030355F3000

and if I read this right than this part must be the kerberos part
F682DBE86C306DC68F5DF461E21CA86841D4560B18F1BE5552B81841AADB5B5C310918A046F9E4B29C2949748F4B38396A008032A0FF27AA0E7C770B493B8A30AC85980250DE2BE36BC75ACBF02C0A76A769EA2AE998F6FD1637A0378B696B2E043FB473A2A5455C9FBA8C5365F39C240B11508814416C0F78075D2C8F222216FF7882874DC82E7791A796BD

with the 4 bytes in front of this (0x8C) the buffer length which is 140 in decimal

**Comment by Kinnay** [comment]
That's interesting. Looks like it uses the updated ticket data format I've only seen on Nintendo Switch servers so far. I guess that's because this game is quite new, as it was released only two years ago.

By the way, there's no problem with sharing your user id. It can be easily requested from the account server anyway (see [/admin/mapped_ids](https://github.com/Kinnay/NintendoClients/wiki/Account-Server#get-adminmapped_ids)). You should never tell anyone your NEX password though.

I'll tell you if I ever find out how you can retrieve your NEX password. I tried to reverse engineer the 3DS friends system module, but haven't found anything useful so far.

**Comment by tastymeatball** [comment]
I guess I found something interesting that has something to do with the kerberos ticket
I looked in the RAM around my user_pid and found an interesting string. I froze the beginning of this string to zero and the game told me that it can't connect to the server after receiving the LoginEx Response from the official server. So I guess this string has something todo with decrypting this kerberos ticket.
I don't if I should post this string here because I don't know if this is some private password or some static value which is for everyone the same. This same string is also found in the friends module RAM at address 0x00198DA8.

**Comment by Kinnay** [comment]
Someone from Pretendo (a group that tries to write a replacement for nintendo network servers when they go down) made a 3DS homebrew app that dumps your NEX password. I haven't tested it myself, but if it works you can use this to get your NEX password.

https://cdn.discordapp.com/attachments/408723233030799362/495588775389560835/Get_PID_Passwrd.7z

**Comment by tastymeatball** [comment]
Tested the homebrew and it works.
and the Password is the same that I found in the RAM and I could successfully decrypt the kerberos part and check the HMAC.
You probably already know that but this longer kerberos part is made of
32 bytes that represent the secure key
4 bytes integer (could be the server pid; 1 in my case)
4 bytes integer (are probably the remaining bytes of the kerberos part; 84 in may case)
4 bytes integer that is the length in bytes of the next part (16 in my case)
"the next part" (16 bytes long in my case)
4 bytes integer that is the length of the kerberos ticket which is probably always 60
60 bytes kerberos ticket

Strangely the the 3DS password doesn't look close to one of the Wii U. The Wii U password just contains lowercase and uppercase letters and numbers but the 3DS password also contains special characters like ? and =
and BTW thank you for your help

**Comment by tastymeatball** [comment]
I don't know if this is a problem in the documentation or I'm reading this wrong

CE0000006D0112000000048000000100000011004D617463686D616B6553657373696F6E00A9000000A500000000270000009F420C00331D1C6C331D1C6C010004005F00000000000000300200000000000005004C756973000374000000020000000600000000000000030000000000000000000000000000000000000001010000000C000000310000C951A83C51281C000001000000640000000000000000001C00000002000000040040535200030105004047495200010300000000000000A884AE8A1F000000010000000000000000

This is a BrowserMatchmakeSession Response all fits well except for the very last value (https://github.com/Kinnay/NintendoClients/wiki/Match-Making-Types#matchmakesession-structure)
A884AE8A1F000000 startedTime
010000 UserPassword
00000000 ReferGid
00 userPWEnabled
00 systemPWEnabled
 Is this normal that the last value is just missing or do I read it wrong

**Comment by Kinnay** [comment]
Nintendo often changes structures when they update the NEX library (especially the MatchmakeSession structure has received lots of changes), and some games even have their own patches. Without looking at the game's code, there's no easy way to determine the NEX version or the structure format. The "only present in" column on the wiki merely consists of guesses based on the games I've looked into so far. If I remember correctly, I extracted most match making types from Super Mario Odyssey, so it's possible that your game uses a slightly different structure format.

I don't think you read it wrong, it's probably an error in the documentation in this case.

**Comment by tastymeatball** [comment]
Ok thank you. Now I know the last value does porbably not exist in my version

**Comment by tastymeatball** [comment]
Sorry I'm misusing this issue to just that it seems that the documentation about the Acknowledgment packets in V0 is not correct. At least for the friend server the ack packet is build like that. The multi ack flag is never set instead its just a normal data packet with the ack flag (3DS always sends a 1 but the Nintendo server sends a 9 with a payload size of 0). The sequence id is not that of the sending machine but instead is the sequence id of the packet that gets acknowledged. And I'm just guessing that the packet signature tells the other end that when it's 0x12345678 this packet is an Acknowledgment.

**Comment by tastymeatball** [comment]
The MPFF Server seems to use to only aggregate acknowledgment. Also it seem to have specify every packet that it acknowledges. If it has to acknowledge 2 packets at once it writes both sequence ids behind each other.

But I have another question. Do you know what Call ID (RMC Protocol) the server uses when he sends a request? This seems to be a special case because I only saw this with the [InitiateProbe](https://github.com/Kinnay/NintendoClients/wiki/NAT-Traversal-Protocol#2-initiateprobe) Request. Also this request gets only acknowledged by the client but it doesn't send an empty response unlike the server does for every request that has no actual response data. Maybe this has something todo with the Call ID or this is just normal behaivior by the client when it gets a response

**Comment by Kinnay** [comment]
The call id shouldn't matter, but this isn't normal behavior either. There's probably something wrong with your RMC request, but I can't tell you what's wrong without seeing the packet you sent to your 3DS.

**Comment by tastymeatball** [comment]
This isn't from my server but from the official server. I try to understand how the UDP hole punching works. And after the Client sends a RequestProbeInitiationExt for every StationURL he gets from GetSessionURLs to the server the server sends to the other client (the Host) a InitiateProbe Request with Call IDs like 0x02C345A7 (frist Probe) or 0x02C345A9 (second Probe)

**Comment by tastymeatball** [comment]
So I got it to work that 3 3DS could join a game in MP FF (4 should probably work too but couldn't test it). The Call ID in the InitiateProbe Request seems to be of no matter. I sent a static 50 in all my requests and the game didn't care. But what I found out is that the RVCID does matter. A 3DS refuses to connect to a device with the exact same RVCID.

BTW the access Key of Pokemon Ultra Sun is 086f9d28 and the Game Server ID is 00164800.

**Comment by tastymeatball** [comment]
I looked a little bit at the packets of Pokemon and found some differences with your documentation. In the MatchmakingExtension(0x6D) Protocol it seems the packets after [WithdrawMatchmakingAll](https://github.com/Kinnay/NintendoClients/wiki/Matchmake-Extension-Protocol#47-withdrawmatchmakingall) are different than in your documentation. I looked at the code and I guess after WithdrawMatchmakingAll follows ClearMyPreviouslyMatchedUserCache instead of FindMatchmakeSessionByGatheringId. If you want to look at the code yourself I can give you the file and the offset where I found it.

**Comment by Kinnay** [comment]
My documentation is based on Super Mario Odyssey, but there are many different versions of the NEX library, and some games even have their own patches. The "common protocols" should be the same in all games and versions, but there may be some differences in the "nintendo only" protocols (for example, the MatchmakeExtension protocol).

**Comment by tastymeatball** [comment]
Don't know if you want to add that to your documentation but Luigi's Mansion 2 seems to be a special canditate when it comes to packet signature calculation. First it doesn't use the the connection signature in the CONNECT packet and second instead of using the connection signature of the other end it uses it's own connection signature.

Also it seems that something is missing in the LoginEx Request. "Newer" (are games that were released 2013 really that new?) games that use the new Kerberos format also use 10 more bytes in the request. Between the Any Data Holder's second length and the token length there are 10 undocumented bytes. The first 6 bytes were always 0 in my received requests. The other 4 seem to be some u32. Luigi's Mansion 2 uses PRUDP1 but uses the old kerberos format. Kid Icarus Uprising uses PRUDP0. The other games in the table are using the PRUDP1 with the new format and these 10 extra bytes.

BTW if you want them to add it, here are the Access Keys of some games. I did verify them.
|Kid Icarus Uprising|00030000|58a7e494|
|Luigi's Mansion 2|00076400|3861a9f8|
|Pokémon X/Y|00055D01|876138df|
|TLoZ Tri Force Heroes|00176E00|c1621b84|

**Comment by Kinnay** [comment]
Thanks, I've added the games to the game server list page.

If you can figure out the exact meaning and format of those unknown fields I'll add them to the wiki too. I don't really want to add incomplete information to the PRUDP/NEX pages.

**Comment by tastymeatball** [comment]
Sorry to bother you again but do you have an idea how to get the nex password of a switch console? I've taken a look at every response that the switch received from servers of nintendo but I didn't found anything that could be the nex password. Maybe its like the 3DS its just saved on the console but I also didn't find any services that could be used to get the password like on the 3DS

**Comment by Kinnay** [comment]
Switch servers are interesting. The password of a normal user account is always "dummy", but you must pass a valid NEX token to [Authentication.LoginEx](https://github.com/Kinnay/NintendoClients/wiki/Authentication-Protocol#2-loginex). Otherwise you get the error Authentication::ValidationFailed. As far as I know, the NEX token can only be obtained from the BaaS server, which can only be accessed after going through DAuth and AAuth (as explained [here](https://github.com/Kinnay/NintendoClients/wiki/NEX-Overview-(Game-Servers)#authentication)).

I've never actually tried to log in on my own account though, so I don't really know the details.

**Comment by tastymeatball** [comment]
I tried the kerberos key derivation with the password dummy and code snippet from this repo. Then tried to decrypt the kerberos ticket with the RC4 initialized with the derived key but the output didn't look like it was decrypted.
The pid I used was my pid a 19 digits long number in base 10
I would give you the encrypted kerberos ticket I have and my pid in private if that is somehow possible

**Comment by Kinnay** [comment]
Make sure you used the new key derivation: `key = MD5(MD5(password) + PACK("<Q", pid))`. You can check if you got the right key by checking the HMAC at the end of the ticket.

It's also possible that I'm wrong about the "dummy" password, since I've never actually tried it (I've never done anything homebrew-related on my Switch yet). If you give me your ticket and pid I can check it.

There's nothing secret in the ticket, and your pid isn't supposed to be secret either. A ticket expires after two minutes, so it can't be used to log in on your account anymore. I think you can safely post it here, but if you still want to send it privately you can send me an email at ymarchand@me.com. You can also find me on Discord and IRC (freenode or EFnet). My username is Kinnay in both places.
