### ISSUE TITLE
Animal Crossing: New Horizons - online islands via dodo code?

### ISSUE THREAD

**Issue by theogravity** [Kinnay/NintendoClients#21]
I noticed that in the wiki, ACNH uses the match making protocol. I was wondering if one of the methods  in the MMP would provide island data for a given dodo code.

**Comment by Kinnay** [comment]
Hi,

I'm pretty sure ACNH uses [BrowseMatchmakeSessionNoHolderNoResultRange](https://github.com/Kinnay/NintendoClients/wiki/Matchmake-Extension-Protocol#52-browsematchmakesessionnoholdernoresultrange) to find an island. The dodo code is in the m_Codeword field of the search criteria structure.

I'd guess that most of the island data is sent to your Switch through the P2P connection, but I also saw some interesting strings in the m_ApplicationBuffer field of the matchmake session that is returned by the server, such as the name of the island.

You're not the first person that wants know how ACNH discovers islands btw, maybe I'll write an example script.

**Comment by Kinnay** [comment]
Here: https://github.com/Kinnay/NintendoClients/blob/master/example_animalcrossing.py

**Comment by theogravity** [comment]
Thank you!

**Comment by theogravity** [comment]
Verified that your script works. Thanks a bunch.
