### ISSUE TITLE
AC:NH credentials

### ISSUE THREAD

**Issue by WinteryFox** [Kinnay/NintendoClients#23]
Is there any method of getting the credentials required for the animal crossing script without rooting your Switch? (I have the new model and thus cannot root it)

**Comment by ThatNerdyPikachu** [comment]
Sadly, it's not possible at this time.

**Comment by Kinnay** [comment]
There used to be a guest account on game servers, but Nintendo deleted it almost a year ago :(

**Comment by WinteryFox** [comment]
Would anyone be so kind as to log into a dummy Nintendo account of mine and give me the credentials for the dodo code script? Add me on Discord if so; 💝 Foxie 💝#0001

**Comment by ThatNerdyPikachu** [comment]
> Would anyone be so kind as to log into a dummy Nintendo account of mine and give me the credentials for the dodo code script? Add me on Discord if so; `💝 Foxie 💝#0001`

The credentials needed aren't just a Nintendo Account, you also would need a legitimate copy of the game, and the consoles PRODINFO, which I don't think anyone would want to share with anyone, as it can get the console in question banned.

**Comment by WinteryFox** [comment]
ah I see, that certainly sucks, thanks for the reply though.

**Comment by WinteryFox** [comment]
what does a console ban entail? would it only prevent you from accessing the eshop and online features? or is it worse?

**Comment by Kinnay** [comment]
If they ban your device you won't ever be able to use that Switch to go online anymore, stopping you from playing games online, using the eShop, friend list and other online features forever.
