### ISSUE TITLE
Obtain .btl file for MM2

### ISSUE THREAD

**Issue by TheGreatRambler** [Kinnay/NintendoClients#28]
According to [this reddit post](https://www.reddit.com/r/SwitchHacks/comments/c6duzc/you_can_now_install_custom_levels_on_mario_maker/?utm_medium=android_app&utm_source=share), three files are neccessary for a level on your savefile:
- bcd (level data)
- dat (replay? data)
- btl (thumbnail data likely)

I am aware you cam download the bcd of any arbitrary level online. How could I aquire the other two and, if not, could I use the default provided by creating a new level in the MM2 editor? Thank you.

**Comment by Kinnay** [comment]
Hi,

Thumbnails are provided by the server as a jpeg file (see example_smm2.py). You probably have to convert them to btl manually.

Replay files can't be downloaded from the server (except for ninji ghosts), but I think you can also use a different replay file, like the default one? I never looked into smm2's save files.

Also just curious, why would you want to add a level to your save file manually? Can't you simply download it on your Switch?

**Comment by TheGreatRambler** [comment]
When you download a level, you lose the ability to edit it. Additionally, WRs obtained on it will get sent back to the original level. The TAS community wants to be able to play popular levels and get TAS WRs on them without affecting the WR of the original level. Thank you for your help!

**Comment by TheGreatRambler** [comment]
I couldn't find this information online, but what is the dimensions of the thumbnail JPEG? I'm trying to get some info about the BTL format.

**Comment by Kinnay** [comment]
Depends on the thumbnail image.
* The "one screen thumbnail" is always 640x360 pixels.

![thumbnail_screen_2003570](https://user-images.githubusercontent.com/10852324/82868035-2bc61280-9f2c-11ea-8b31-5804514fb16d.jpg)

* The "entire thumbnail" is always 144 pixels high. The width depends on the size of the level, but I think it's always between 128 and 1280 pixels.

![thumbnail_entire_2003570](https://user-images.githubusercontent.com/10852324/82868205-87909b80-9f2c-11ea-8485-adc04ceed166.jpg)
