### ISSUE TITLE
How do you extract the Switch's client certificate for MITM?

### ISSUE THREAD

**Issue by iomintz** [Kinnay/NintendoClients#32]
Hi, I'd like to MITM my Switch in order to try and figure out how some of these APIs work. I set up Charles, configured my Switch to proxy to it, and added a patch which disables certificate verification. It's working, sorta. I'm told I need my Switch's client certificate to get more detailed logging of requests. How do I get that? I tried using SimonMKWii's scripts but got a NameError. Then I tried using [CertNXtractionPack](https://gist.github.com/SocraticBliss/4410790b6e5a27161f521c45d1eb2684) but Charles refuses to read the resulting PFX file (I tested Firefox just in case it's a Charles error, no dice there either). Can you recommend a better way to get my Switch's client certificate?

**Comment by Kinnay** [comment]
Hi,

Maybe this helps?

```python
from nintendo.switch import ProdInfo, KeySet
from nintendo.common import ssl

keys = KeySet("/path/to/prod.keys")
info = ProdInfo(keys, "/path/to/PRODINFO")

cert = info.get_ssl_cert()
pkey = info.get_ssl_key()

with open("device_cert.crt", "wb") as f:
	f.write(cert.encode(ssl.TYPE_PEM))
with open("device_cert.key", "wb") as f:
	f.write(pkey.encode(ssl.TYPE_PEM))
```

By the way, you only need the client certificate for `dauth-lp1.ndas.srv.nintendo.net` as far as I'm aware. You should be able to see the details of the other requests without client certificate if you have enabled SSL proxying.

**Comment by iomintz** [comment]
Thank you. This worked. As for not needing it after all, turns out I hadn't enabled SSL proxying for all domains in my MITM tool. Whoops!

**Comment by ckbaker10** [comment]
Updated Version



```
from nintendo import switch
from anynet import tls


keys = switch.load_keys("prod.keys")
info = switch.ProdInfo(keys, "..._PRODINFO.bin")

cert = info.get_tls_cert()
pkey = info.get_tls_key()

cert.save("device_cert.pem",tls.TYPE_PEM)
pkey.save("device_cert.key",tls.TYPE_PEM)
```

**Comment by rama0dev** [comment]
Do u know how extract from Mariko NX?

**Comment by xGOBx** [comment]
> Do u know how extract from Mariko NX?

did you ever find this out

**Comment by rama0dev** [comment]
You can skip step with certificates for logging requests, ik thats it can make more insecure, but after 1 year logging, my switch is still not banned.
