### ISSUE TITLE
ACNH: how to search for friends with open gates?

### ISSUE THREAD

**Issue by ioistired** [kinnay/NintendoClients#40]
It'd be great to be able to search for open islands without a Dodo Code. What is the process for that?

**Comment by iomintz** [comment]
Any update on this? It's now more useful to me as I want to find out how to become someone's friend without having to bot visiting their island and leaving again.

**Comment by Kinnay** [comment]
Sorry I have very little time at the moment because of my bachelor's thesis. I also want to redesign the code with an async library before I implement any new features, because the current scheduler is really broken. You'll have to figure this out on your own for now.

**Comment by iomintz** [comment]
ok

**Comment by iomintz** [comment]
well, I'll leave this open as a reminder for me to figure it out.

**Comment by Kinnay** [comment]
I figured it out. The game calls [`FindMatchmakeSessionByParticipant`](https://github.com/Kinnay/NintendoClients/wiki/Matchmake-Extension-Protocol#51-findmatchmakesessionbyparticipant). The friend pids are probably obtained from the baas server (2.0.0/users/&lt;id&gt;/friends).

**Comment by kinnay** [comment]
I implemented 2.0.0/users/&lt;id&gt;/friends: https://github.com/kinnay/NintendoClients/commit/71d77bb086c330be80df155b4eb26767a27664d2
