### ISSUE TITLE
SMM Data Store methods

### ISSUE THREAD

**Issue by mrexodia** [Kinnay/NintendoClients#6]
Updates to https://github.com/Kinnay/NintendoClients/wiki/Data-Store-Protocol-(SMM)

```c++
#include "CommonTypes.bt"

struct Unknown_0x004a_request {
    uint32 id; //observed values: 0x82, 0x81, 0x80
};

struct Unknown_0x004a_response {
    uint32 size;
    qBuffer data[size] <optimize=false>;
};
```

**Comment by mrexodia** [comment]
```c++
#include "CommonTypes.bt"

struct Unknown_0x003d_request {
    uint32 id; //observed values: 0, 1, 2
};

struct Unknown_0x003d_response {
    uint32 size;
    uint32 data[size] <optimize=false>;
};
```

**Comment by mrexodia** [comment]
```c++
#include "CommonTypes.bt"

struct Unknown_0x0041_request {
    GenericStruct unk1;
    qVector_qBuffer unk2;
};
```

**Comment by mrexodia** [comment]
Here is a repository: https://github.com/mrexodia/SMMNEX

**Comment by Kinnay** [comment]
`Unknown_0x0041_request` doesn't match up with what I found in the RPX and my packet dumps. I updated the wiki page with what I believe to be the right format. I documented all methods I could find in the RPX btw.

**Comment by mrexodia** [comment]
For me your struct does not match whatsoever. Are you on SMM 1.47? This is my request bytes for Method 0x41 (65):

```
014d00000001010000002f4f03680000000000fffffb7e3f3f9c000000fb7e3f3f9c000000fb7e3f3f9c000000fb7e3f3f9c00000000000000000000000000000800000000000000640000002700000000000d00000002003000020033000300313000020034000300313100020035000300313200020036000300313300020037000300313400020038000300313500
```

**Comment by Kinnay** [comment]
That looks very similar to my own payload. I just noticed a mistake in my docs though: all `DataStoreChangeMetaCompareParam` should be `List<string>` instead. Fixing that right now.

**Comment by Kinnay** [comment]
Ok, I updated the wiki. I also compared it against our packets again and it seems to exactly match the docs now.

**Comment by mrexodia** [comment]
With regards to the RE, how do you figure out the packets so quickly? :smile: I imported some binaries with symbols into Kam1n0 to allow me to search for similar functions, but it's annoying to figure out (especially without looking at the payload):

For Method74 it's fairly straightforward on the request side:

![](https://i.imgur.com/t06KIkr.png)

For the response it's pretty difficult without symbols. Kam1n0 helps, but the percentages are not very reliable, so I guess looking at the payload would have resolved that issue (but I only have an empty payload response in my packet captures):

![](https://i.imgur.com/acWfuJn.png)

So in the end it looks like this:

![](https://i.imgur.com/LORZWZq.png)

I don't think I would have arrived at this conclusion without your wiki to help though (not knowing anything about PPC doesn't help much either), so I'm interested in your workflow. You mentioned you use Lost Reaver's symbols. Do you just manually match them or are there any other tools I'm not aware of that can help with matching them?

**Comment by Kinnay** [comment]
I've written a few scripts that help with the initial analysis (for example, one that converts all bytes in the .text segments to code because IDA mistakenly marks it as data sometimes) and repetitive or annoying tasks. Other than that, I do almost everything manually.

I only used lost reavers to find out where the datastore methods are located. After that, I analyzed the methods by hand. I've seen these methods often enough that I can recognize them easily. I don't even have a decompiler for PPC so I'm just looking at the plain assembly code 🙂

**Comment by Kinnay** [comment]
I figured out lots of method names. I removed the request/response docs for now, because it'd take some work to update all the names and links properly, but you can still see them in the revision history of course.

**Comment by mrexodia** [comment]
Thanks! I'll try updating my smm protocol file and rebase on the latest master because I see there have been quite a few updates.

**Comment by Kinnay** [comment]
Tasty discovered that SMM 3DS has DDL parse trees, so the data store protocol is completely documented now!

**Comment by mrexodia** [comment]
Great news!
