### ISSUE TITLE
[Request] Add script for download codes from:

### ISSUE THREAD

**Issue by cualquiercosa327** [kinnay/NintendoClients#62]
- Smile Basic 4
- Fuze player / Fuze 4
-  Game Builder Garage

It would be very useful for people who can no connect to Nintendo servers 
with a Switch. 
A lot of thanks

**Comment by kinnay** [comment]
Hi,

I will probably write a sample script for Game Builder Garage.

> It would be very useful for people who can no connect to Nintendo servers with a Switch

If your Switch is banned, or if you don't have a Switch at all, there is no way to connect to Nintendo servers. Even the scripts on this repository can't get around device and application authentication. That's why they require your device certificate and game ticket.

**Comment by kinnay** [comment]
See [gamebuilder.py](https://github.com/kinnay/NintendoClients/blob/master/examples/switch/gamebuilder.py).

I've never played Smile Basic 4 and Fuse 4, but if they use NEX then you can probably download games/programs in a similar way.

**Comment by cualquiercosa327** [comment]
Hi, thanks.
I own a switch but since I installed Atmosphere I have never connect to Internet. 
I must look the smario35 tutorial and try.

Thanks for adding Game Building support. About the others I am no sure
what protocol they use. On the past I tried to mod the vibration file from Smile Basic for adding custom ones ( or reusing some of other games as kazuate of 1 2 switch and build a program myself replying it).

**Comment by kinnay** [comment]
> About the others I am no sure what protocol they use.

I don't know either, sorry. I'd guess that they use NEX + the data store protocol (just like Game Builder Garage), because almost all games use that, but I can't look it up for you because I haven't bought these games.

**Comment by cualquiercosa327** [comment]
Hi Fuze Player is free

**Comment by kinnay** [comment]
It's **almost** free. On my Switch it costs &euro; 0,99. Of course that's almost nothing, but I don't want to buy games unless I want to play them.

The example scripts on this repo are also not supposed to cover every single Switch game. They show how one can interact with NEX servers, but game specific features are not in the scope of this repository, unless it's a first party game that I care about.

You have to do your own research here, or ask someone else.

**Comment by cualquiercosa327** [comment]
Oh, excuse me for my mistake : I own the full version and I thought the player was free.
Of course I understand you, as I do the same: I buy only the games I have interest in (and it it is physical, better).
Thanks and excuse me for my mistake

**Comment by cualquiercosa327** [comment]
Hello.
Excuse me for asking you again but I would know if they are a chance you support this programs if I buy them for you?
Thanks
________________________________
De: Yannik Marchand ***@***.***>
Enviado: domingo, 13 de junio de 2021 14:10
Para: kinnay/NintendoClients ***@***.***>
Cc: cualquiercosa327 ***@***.***>; Author ***@***.***>
Asunto: Re: [kinnay/NintendoClients] [Request] Add script for download codes from: (#62)


It's almost free. On my Switch it costs € 0,99. Of course that's almost nothing, but I don't want to buy games unless I want to play them.

The example scripts on this repo are also not supposed to cover every single Switch game. They show how one can interact with NEX servers, but game specific features are not in the scope of this repository, unless it's a first party game that I care about.

You have to do your own research here, or ask someone else.
