### ISSUE TITLE
Add support for 12.1.0

### ISSUE THREAD

**Issue by kinnay** [kinnay/NintendoClients#64]
See title. Dump the account sysmodule and check if anything has changed. Apparently there is a new master key.

**Comment by kinnay** [comment]
See 0c2e0535610ae328bafd18d6951d420629987b0b. The account sysmodule seems to be identical.

**Comment by v8mpower** [comment]
hello kinnay, any hint why do I get error "Error: privk does not appear to be inverse of pubk!" when trying to create a certificate using my prodinfo and keys? Could it be that these come for Mariko switch or 12.1.0 still got something changed?

**Comment by kinnay** [comment]
Hi,
Prodinfo hasn't changed in 12.1.0 as far as I know. You are using [this](https://gist.github.com/SciresM/c393d27caf18675bcb2475569bb864dd) script right? It seems like either your private key is wrong, or the script is extracting the wrong public key from your certificate, but I can't really help you unless you give me more details on what you did. Also, I'm not the person who wrote that script. You might want to ask SciresM instead.

**Comment by v8mpower** [comment]
Hello, just a quick update, I did exactly the same procedure and it works with erista to extract the cert

**Comment by kinnay** [comment]
That does sound like Mariko got something changed. [Switchbrew](https://switchbrew.org/wiki/Calibration) doesn't mention any differences though. I don't think I can help you with this, sorry.
