### ISSUE TITLE
Missing secureprotocol method handle

### ISSUE THREAD

**Issue by TudouHack** [kinnay/NintendoClients#74]
SecureConnectionProtocol is missing UpdateURLs and protocol ids for replace_url and send_report are incorrect because of it either
![image](https://user-images.githubusercontent.com/39432598/147967140-1b2ee379-4408-440a-a0b5-d424e72bd4a4.png)
![image](https://user-images.githubusercontent.com/39432598/147967197-c5cb4e64-e7d5-41b3-b2bb-bd228f031d35.png)

**Comment by kinnay** [comment]
You're right, thank you. I fixed this. I hope this solves your Splatoon 2 issues.
