### ISSUE TITLE
Wiki: znc.srv.nintendo.net does not appear to be voice traffic as stated

### ISSUE THREAD

**Issue by adamwelsh** [kinnay/NintendoClients#78]
Please verify the actual usage of this URL: znc.srv.nintendo.net
I see a lot of short flows with low data to *.znc.srv.nintendo.net that do not appear to be voice chat flows.
Additionally, this reverse engineering project points to the URL being used for different functions in the online lounge, not necessarily related to voice: https://github.com/ZekeSnider/NintendoSwitchRESTAPI

Further clarity would be helpful.

**Comment by kinnay** [comment]
Thanks, you're probably right. I guess that this server provides an API for the smartphone app, and voice chat is just one of its services. I updated the wiki.
