### ISSUE TITLE
Wii U - Mario Maker 1 - Get Course Example

### ISSUE THREAD

**Issue by TheCryptan** [kinnay/NintendoClients#96]
First off I want to say thank you so much for creating NintendoClients, I currently use it in the Team 0% (SMM1/2 Discord) to bulk scrape all uncleared Mario Maker 2 levels and that wouldn't be possible without your work here. 

We've managed to recently come across an archive of MM1 uncleared levels that was extracted from the bookmark site & I was wondering if you had an example of getting course information (mostly interested in clears) for a Mario Maker 1 level on Wii U?

I see you already have datastore_smm.py implemented, so it would be really useful to have an example 😄

**Comment by jonbarrow** [comment]
You'll probably find this useful/interesting. Im the lead developer of Pretendo Network and we've done this kind of scraping for MM1 already to archive all uploaded courses after the ability to upload was disabled

The script uses NintendoClients to do the scraping, though it uses an older version so you may need to update some things

https://github.com/PretendoNetwork/smm1-course-archive

**Comment by TheCryptan** [comment]
Thanks so much! I'll check it out once my Wii U arrives 😬
